# Generated by Django 2.1.14 on 2020-03-14 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioSeguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_inicio', models.DateField()),
                ('dia_fin', models.DateField()),
            ],
            options={
                'verbose_name': 'Calendario Seguimiento',
                'verbose_name_plural': '4. Calendario Seguimiento',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numeroPoblacion', models.IntegerField()),
                ('estado', models.CharField(choices=[('C', 'Controlado'), ('E', 'Emergencia'), ('Q', 'Cuarentena'), ('X', 'Endemica')], default='C', max_length=1)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': '2. Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateField()),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': '9 Contacto',
            },
        ),
        migrations.CreateModel(
            name='DiaSeguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateTimeField()),
                ('calendario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviciotrazacov2.CalendarioSeguimiento')),
            ],
            options={
                'verbose_name': 'Dia Seguimiento',
                'verbose_name_plural': '6 Dias de Seguimiento',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('continente', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': '1. Paises',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('paterno', models.CharField(max_length=120)),
                ('materno', models.CharField(max_length=120)),
                ('edad', models.IntegerField()),
                ('dni', models.CharField(max_length=15)),
                ('pasaporte', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': '3. Personas',
            },
        ),
        migrations.CreateModel(
            name='PersonaContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('paterno', models.CharField(blank=True, max_length=80, null=True)),
                ('materno', models.CharField(blank=True, max_length=80, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('referencia_ubicacion', models.CharField(blank=True, max_length=500, null=True)),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviciotrazacov2.Contacto')),
            ],
            options={
                'verbose_name': 'PersonaContacto',
                'verbose_name_plural': '9 Personas Contacto',
            },
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.IntegerField()),
                ('longitud', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Posicion',
                'verbose_name_plural': '7 Posiciones',
            },
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField()),
                ('dolor_garganta', models.BinaryField()),
                ('congestion_nasal', models.BinaryField()),
                ('secreccion_nasal', models.BinaryField()),
                ('tos_seca', models.BinaryField()),
                ('cansancio', models.BinaryField()),
                ('dificultad_respirar', models.BinaryField()),
                ('diarrea', models.BinaryField()),
            ],
            options={
                'verbose_name': 'Sintoma',
                'verbose_name_plural': '5. Sintomas',
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('A', 'Auto'), ('B', 'Bus Viaje'), ('C', 'Bus Urbano'), ('D', 'Taxi'), ('E', 'Avion'), ('F', 'Fluvial'), ('G', 'Barco'), ('H', 'Moto')], max_length=1)),
                ('numero_pasajeros', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Transporte',
                'verbose_name_plural': '9 Transporte',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ubicacion', models.CharField(choices=[('D', 'Departamento'), ('C', 'Cuarto'), ('H', 'Habitacion'), ('A', 'Casa'), ('E', 'Trabajo'), ('U', 'Escuela'), ('X', 'Exterior'), ('M', 'Mercado')], default='D', max_length=1)),
                ('direccion', models.CharField(max_length=200, null=True)),
                ('posicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviciotrazacov2.Posicion')),
            ],
            options={
                'verbose_name': 'Ubicacion',
                'verbose_name_plural': '8 Ubicaciones',
            },
        ),
        migrations.AddField(
            model_name='diaseguimiento',
            name='sintoma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviciotrazacov2.Sintoma'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='posicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviciotrazacov2.Posicion'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='transporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviciotrazacov2.Transporte'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviciotrazacov2.Ubicacion'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='pais_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviciotrazacov2.Pais'),
        ),
        migrations.AddField(
            model_name='calendarioseguimiento',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviciotrazacov2.Persona'),
        ),
    ]
